server {
    listen 80 default_server;
    server_name _;

    root /var/www;
    autoindex on;

    location /clamav/ {
        alias /var/www/clamav/;
        autoindex on;
    }

    location = /healthz {
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }
}
